# Generated by Django 4.2 on 2023-05-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='home_page',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='home page'),
        ),
    ]
