# Generated by Django 4.2 on 2023-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_appuser_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='home_page',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='home page'),
        ),
    ]
