# Generated by Django 4.2 on 2023-05-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_appuser_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='guest',
            field=models.BooleanField(default=False, verbose_name='guest'),
        ),
    ]
