# Generated by Django 4.2 on 2023-05-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_guestuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='guest',
        ),
    ]
