# Generated by Django 4.2 on 2023-05-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_remove_comment_guest_alter_comment_user'),
        ('user', '0006_remove_appuser_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestUser',
        ),
    ]
