# Generated by Django 4.2 on 2023-05-09 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0004_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rated_users',
            field=models.ManyToManyField(related_name='rated_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
