# Generated by Django 4.2 on 2023-05-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_rated_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.SmallIntegerField(default=0),
        ),
    ]
