# Generated by Django 4.2 on 2023-05-10 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_guestuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0006_alter_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.guestuser'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
